### ISSUE TITLE
Multi person configuration or not

### ISSUE THREAD

**Issue by yuanshengaoshou114** [NotThorny/AttackModifier#13]
I am using a translator, and multiple players use one profile, which makes it impossible for players to customize enabling or disabling. Can you distinguish profiles?

**Comment by NotThorny** [comment]
I will look into possible implementation for this.

**Comment by NotThorny** [comment]
Added per-user enabling and disabling of effects in [release v1.2](https://github.com/NotThorny/AttackModifier/releases/tag/1.2)

**Comment by yuanshengaoshou114** [comment]
> Added per-user enabling and disabling of effects in [release v1.2](https://github.com/NotThorny/AttackModifier/releases/tag/1.2)

I use mechanical translation, sorry
Last time you repaired it, this new version still cannot be used, causing a white screen. Can you repair it again? The switches have been distinguished. Can each player distinguish the special effects?

**Comment by NotThorny** [comment]
I went ahead and built it with docker again so it should fix that.
[AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/10348298/AttackModifier.zip)

As far as having different effects for each player saved to file, it would likely end up requiring each player to have their own file. That could end up being a lot of files if you have a lot of players, but it should be possible. 
Before doing that, using `/at set` should make each different player have their own effects, but they wouldn't be saved to the file. That would mean needing to set them again at every login.

If you are ok with there being a lot of additional files for each user then I can look into implementing individual effects as well.

**Comment by yuanshengaoshou114** [comment]
> 

Cool! Multiple profiles are not a problem! Thank you very much for your repair! thank you very much indeed

**Comment by yuanshengaoshou114** [comment]
> I went ahead and built it with docker again so it should fix that. [AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/10348298/AttackModifier.zip)
> 
> As far as having different effects for each player saved to file, it would likely end up requiring each player to have their own file. That could end up being a lot of files if you have a lot of players, but it should be possible. Before doing that, using `/at set` should make each different player have their own effects, but they wouldn't be saved to the file. That would mean needing to set them again at every login.
> 
> If you are ok with there being a lot of additional files for each user then I can look into implementing individual effects as well.

<INFO:AttackModifierCommand> Invalid or missing config for: amborIds
> java.lang.NoSuchFieldException: amborIds
        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
        at thorny.grasscutters.AttackModifier.commands.AttackModifierCommand$getCharacter.getCurrent(AttackModifierCommand.java:216)
        at thorny.grasscutters.AttackModifier.commands.AttackModifierCommand.addAttack(AttackModifierCommand.java:139)
        at thorny.grasscutters.AttackModifier.EventListener.onPacket(EventListener.java:39)
        at emu.grasscutter.plugin.PluginManager.invokeHandler(PluginManager.java:324)
        at emu.grasscutter.plugin.PluginManager.lambda$checkAndFilter$7(PluginManager.java:269)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at emu.grasscutter.plugin.PluginManager.checkAndFilter(PluginManager.java:269)
        at emu.grasscutter.plugin.PluginManager.lambda$invokeEvent$4(PluginManager.java:251)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.plugin.PluginManager.invokeEvent(PluginManager.java:251)
        at emu.grasscutter.server.event.Event.call(Event.java:30)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:83)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:214)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:73)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yuanshengaoshou114** [comment]
> I went ahead and built it with docker again so it should fix that. [AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/10348298/AttackModifier.zip)
> 
> As far as having different effects for each player saved to file, it would likely end up requiring each player to have their own file. That could end up being a lot of files if you have a lot of players, but it should be possible. Before doing that, using `/at set` should make each different player have their own effects, but they wouldn't be saved to the file. That would mean needing to set them again at every login.
> 
> If you are ok with there being a lot of additional files for each user then I can look into implementing individual effects as well.

<ERROR:GameServerPacketHandler> Error: handle
java.lang.NullPointerException: Cannot read field "skill" because "currentAvatar" is null
        at thorny.grasscutters.AttackModifier.commands.AttackModifierCommand.addAttack(AttackModifierCommand.java:149)
        at thorny.grasscutters.AttackModifier.EventListener.onPacket(EventListener.java:39)
        at emu.grasscutter.plugin.PluginManager.invokeHandler(PluginManager.java:324)
        at emu.grasscutter.plugin.PluginManager.lambda$checkAndFilter$7(PluginManager.java:269)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at emu.grasscutter.plugin.PluginManager.checkAndFilter(PluginManager.java:269)
        at emu.grasscutter.plugin.PluginManager.lambda$invokeEvent$4(PluginManager.java:251)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.plugin.PluginManager.invokeEvent(PluginManager.java:251)
        at emu.grasscutter.server.event.Event.call(Event.java:30)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:83)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:214)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:73)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NotThorny** [comment]
Fixed Amber and the other error that was causing
[AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/10361980/AttackModifier.zip)

**Comment by NotThorny** [comment]
I've added multi-person configurations in [version 1.3](https://github.com/NotThorny/AttackModifier/releases/tag/1.3). I've also included a jar for docker in releases, "Docker-AttackModifier.jar".

**Comment by yuanshengaoshou114** [comment]
> I've added multi-person configurations in [version 1.3](https://github.com/NotThorny/AttackModifier/releases/tag/1.3). I've also included a jar for docker in releases, "Docker-AttackModifier.jar".

21:29:32 <INFO:AddAttack> Invalid or missing config for: noelIds
> java.lang.NoSuchFieldException: noelIds
        at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
        at thorny.grasscutters.AttackModifier.AddAttack$getCharacter.getCurrent(AddAttack.java:139)
        at thorny.grasscutters.AttackModifier.AddAttack.addAttack(AddAttack.java:59)
        at thorny.grasscutters.AttackModifier.EventListener.onPacket(EventListener.java:38)
        at emu.grasscutter.plugin.PluginManager.invokeHandler(PluginManager.java:324)
        at emu.grasscutter.plugin.PluginManager.lambda$checkAndFilter$7(PluginManager.java:269)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at emu.grasscutter.plugin.PluginManager.checkAndFilter(PluginManager.java:269)
        at emu.grasscutter.plugin.PluginManager.lambda$invokeEvent$4(PluginManager.java:251)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.plugin.PluginManager.invokeEvent(PluginManager.java:251)
        at emu.grasscutter.server.event.Event.call(Event.java:30)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:83)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:214)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:73)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NotThorny** [comment]
I fixed that config, and also checked to make sure all the other characters were still correct, so you shouldn't see this error anymore. I updated the release jar, but here it is as well.
[Docker-AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/10369251/Docker-AttackModifier.zip)
