### ISSUE TITLE
Plugin bug

### ISSUE THREAD

**Issue by yuanshengaoshou114** [NotThorny/AttackModifier#15]
Use the latest 3.6grasscutter, as well as the latest plugins
Use grasscutter ishttps://github.com/YuukiPS/Grasscutters-Original
05:02:16 <WARN:SingleThreadEventExecutor$4> Unexpected exception from an event executor:
java.lang.NoSuchMethodError: 'emu.grasscutter.data.excels.AvatarSkillDepotData emu.grasscutter.game.avatar.Avatar.getSkillDepot()'
        at thorny.grasscutters.AttackModifier.AddAttack.addAttack(AddAttack.java:39)
        at thorny.grasscutters.AttackModifier.EventListener.onPacket(EventListener.java:38)
        at emu.grasscutter.plugin.PluginManager.invokeHandler(PluginManager.java:309)
        at emu.grasscutter.plugin.PluginManager.lambda$checkAndFilter$7(PluginManager.java:254)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at emu.grasscutter.plugin.PluginManager.checkAndFilter(PluginManager.java:254)
        at emu.grasscutter.plugin.PluginManager.lambda$invokeEvent$4(PluginManager.java:237)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.plugin.PluginManager.invokeEvent(PluginManager.java:237)
        at emu.grasscutter.server.event.Event.call(Event.java:21)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:89)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:224)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:73)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by NotThorny** [comment]
Updated to work with the reworked data system used by Yuuki's Grasscutter.

[AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/11437257/AttackModifier.zip)
