### ISSUE TITLE
Plugin bug

### ISSUE THREAD

**Issue by yuanshengaoshou114** [NotThorny/AttackModifier#16]
Use the latest 3.6grasscutter, as well as the latest plugins
Use grasscutter ishttps://github.com/YuukiPS/Grasscutters-Original

AttackModifier
java.lang.NoClassDefFoundError: emu/grasscutter/utils/EventConsumer
        at thorny.grasscutters.AttackModifier.AttackModifier.onEnable(AttackModifier.java:31)
        at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$2(PluginManager.java:205)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:201)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:181)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.utils.EventConsumer
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 5 common frames omitted

**Comment by NotThorny** [comment]
Updated with latest data changes:
[AttackModifier.zip](https://github.com/NotThorny/AttackModifier/files/11525127/AttackModifier.zip)
